# Generated by Django 4.2.2 on 2023-06-21 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='income',
            name='date',
        ),
        migrations.RemoveField(
            model_name='income',
            name='discription',
        ),
        migrations.AddField(
            model_name='income',
            name='other',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='source_1',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='source_2',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userdata'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField(default=None, null=True)),
                ('electric', models.IntegerField(default=None, null=True)),
                ('gas', models.IntegerField(default=None, null=True)),
                ('cell_phone', models.IntegerField(default=None, null=True)),
                ('groceries', models.IntegerField(default=None, null=True)),
                ('car_payment', models.IntegerField(default=None, null=True)),
                ('credit_cards', models.IntegerField(default=None, null=True)),
                ('auto_insurance', models.IntegerField(default=None, null=True)),
                ('miscellaneous', models.IntegerField(default=None, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
            ],
        ),
    ]
