# Generated by Django 4.2.2 on 2023-07-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_expense_year_alter_income_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.IntegerField(default=7),
        ),
        migrations.CreateModel(
            name='ExpenseLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=7)),
                ('year', models.IntegerField(default=2023)),
                ('rent_limit', models.IntegerField(default=None, null=True)),
                ('electric_limit', models.IntegerField(default=None, null=True)),
                ('gas_limit', models.IntegerField(default=None, null=True)),
                ('cell_phone_limit', models.IntegerField(default=None, null=True)),
                ('groceries_limit', models.IntegerField(default=None, null=True)),
                ('car_payment_limit', models.IntegerField(default=None, null=True)),
                ('credit_cards_limit', models.IntegerField(default=None, null=True)),
                ('auto_insurance_limit', models.IntegerField(default=None, null=True)),
                ('miscellaneous_limit', models.IntegerField(default=None, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
            ],
        ),
    ]
